[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/api/momentum-history"
  to = "/.netlify/functions/momentum-history"
  status = 200

[[redirects]]
  from = "/api/ticker"
  to = "/.netlify/functions/ticker"
  status = 200

[[redirects]]
  from = "/api/volatility"
  to = "/.netlify/functions/volatility"
  status = 200
